//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShamimHomeAssingment.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShamimHomesAssingmentEntities : DbContext
    {
        public ShamimHomesAssingmentEntities()
            : base("name=ShamimHomesAssingmentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<StudentClass> StudentClasses { get; set; }
        public virtual DbSet<StudentTable> StudentTables { get; set; }
    }
}
